# Generated by Django 3.2.6 on 2022-03-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220316_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='intervieweEndTime',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='schedule',
            name='intervieweStartTime',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
