# Generated by Django 3.2.6 on 2022-03-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220317_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='allinterviewers',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
