# Generated by Django 3.2.12 on 2022-09-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_schedule_allinterviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='interviewDate',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
