# Generated by Django 3.2.6 on 2022-11-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220917_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(blank=True, max_length=100)),
                ('candidate_email', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
