# Generated by Django 3.2.6 on 2022-11-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='interview_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.schedule'),
        ),
    ]
