# Generated by Django 3.2.6 on 2022-11-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_candidates_interview_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='interview_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='candidates',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.candidates'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
